name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Create local.properties
      run: echo "sdk.dir=$ANDROID_HOME" > local.properties
    
    - name: Create assets directory
      run: mkdir -p app/src/main/assets
    
    - name: Create dummy TensorFlow Lite model
      run: touch app/src/main/assets/game_character_model.tflite
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug
      
    # تبسيط سير العمل بإزالة خطوة رفع الملف التي تسبب المشكلة
    # سنقوم بإعادة إضافتها لاحقاً بعد نجاح البناء الأساسي
