name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    # استبدال خطوة إعداد Android SDK بأوامر مباشرة
    - name: Setup Android SDK
      run: |
        echo "تثبيت أدوات Android SDK الأساسية"
        echo y | sudo apt-get install -y --no-install-recommends lib32stdc++6 lib32z1
        
    - name: Build with Gradle
      run: ./gradlew assembleDebug --stacktrace
      
    # تفعيل خطوة رفع الملفات
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/*.apk
